### ISSUE TITLE
github basecamp integration

### ISSUE THREAD

**Issue by lizadams** [CEMPD/Playbook#1]
Tried following these directions to integrate basecamp and github
Goal is to have a new todo item in basecamp automatically create an issue in github

**Comment by lizadams** [comment]
https://developer.github.com/webhooks/
Need to review this documentation to determine if the website that I am using for basecamp is correct.

**Comment by michellegrace** [comment]
The new basecamp3 is awesome, but is not free if we want to create multiple basecamp projects.

**Comment by michellegrace** [comment]
I ultimately deleted the basecamp once I realize this would not work for multiple projects. I added language to this effect on the slides we are preparing.
